name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          timeout: 30s
          script: |
            cd /home/Admin/stresser
            git config --global --add safe.directory /home/Admin/stresser
            sudo chown -R Admin:Admin /home/Admin/stresser
            git pull origin main
            rm -rf node_modules package-lock.json .next
            npm install --legacy-peer-deps
            npm run build
            sudo -u Admin pm2 restart stresser || pm2 restart stresser
            sudo -u Admin pm2 save || pm2 save

